### ISSUE TITLE
load function declared twice

### ISSUE THREAD

**Issue by gcandal** [hivesolutions/yonius#19]
There are 2 conflicting exports of a `load` function:
- https://github.com/hivesolutions/yonius/blob/dac7219d73c45a56e2ad58459e071060dcd17227/js/util/config.js#L54 (this is the one being actually exported)
- https://github.com/hivesolutions/yonius/blob/dac7219d73c45a56e2ad58459e071060dcd17227/js/base/main.js#L6

I'm not seeing any problem in practice, just stumbled upon it when trying to write type definitions.

**Comment by gcandal** [comment]
@joamag can't assign it to you.

**Comment by joamag** [comment]
@gcandal can you create a simple unit test to avoid regressions?

**Comment by joamag** [comment]
This is not an issue as an alias is being created here 

https://github.com/hivesolutions/yonius/blob/643c6c5719bf71b82350351fb6c3e4de36b832d2/js/util/index.js#L7
