### ISSUE TITLE
CoreMongooseArray exposed to the user

### ISSUE THREAD

**Issue by gcandal** [hivesolutions/yonius#32]
## Description

When fetching arrays from the database, users will receive `[CoreMongooseArray](https://github.com/Automattic/mongoose/blob/master/lib/types/core_array.js)` rather than a plain `Array`. Even though the former seems to be a superset, and even if we ignore the abstraction leak, it might still prove problematic for instance when doing comparisons.

**Comment by gcandal** [comment]
@joamag

**Comment by joamag** [comment]
True, should provide normalized data structures and not specialized ones

**Comment by joamag** [comment]
@gcandal can you take a look at this ?

**Comment by joamag** [comment]
@gcandal just pinging ;)

**Comment by joamag** [comment]
Closing this as wont fix as this is not relevant
